version: '3.9'

services:
  app:
    container_name: graphql-api
    image: nest-graphql
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev app
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
