version: '3.9'

services:
  app:
    container_name: graphql-api
    image: nest-graphql
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev app
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - elasticsearch

  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_NAME}']

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl --silent --fail localhost:9200/_cluster/health || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata: {}
  redis:
    driver: local
